// PDF document branding — standalone page (extracted from Project Settings
// tabs because PDF setup deserves its own home, not a buried tab). Applies
// to invoices, acts, receipts and tickets — every PDF generated by the
// backend renders with these values stamped into the header / footer /
// accent stripes.
//
// Design mirrors the Product Settings "bulk-style" layout: one hero banner
// at top + Section components with icon / title / subtitle + bulk-field
// cards. Save-on-change for each field — no "Save all" button at the
// bottom. Toast pops on every successful save.

import { useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useOutletContext } from 'react-router-dom';
import {
  FileText, Buildings, IdentificationBadge, Palette, UploadSimple,
  EnvelopeSimple,
} from '@phosphor-icons/react';
import { API_BASE } from '../../api.js';
import '../../Style/Authentication.css';
import '../../Style/Products.css';

const STYLE_OPTIONS = [
  { key: 'modern',  label: 'Modern',  hint: 'Coloured banner + accent stripes (default).' },
  { key: 'classic', label: 'Classic', hint: 'Centered, serif, formal — invoice-style.' },
  { key: 'minimal', label: 'Minimal', hint: 'Black & white, no decoration, prints small.' },
];

function StyleCard({ option, current, onPick }) {
  const active = option.key === current;
  return (
    <button type="button"
      className={`doc-style-card${active ? ' doc-style-card--active' : ''}`}
      onClick={() => onPick(option.key)}>
      <div className={`doc-style-preview doc-style-preview--${option.key}`}>
        <div className="doc-style-preview-band" />
        <div className="doc-style-preview-line doc-style-preview-line--w70" />
        <div className="doc-style-preview-line doc-style-preview-line--w50" />
        <div className="doc-style-preview-line doc-style-preview-line--w90" />
        <div className="doc-style-preview-line doc-style-preview-line--w60" />
      </div>
      <div className="doc-style-name">{option.label}</div>
      <div className="doc-style-hint">{option.hint}</div>
    </button>
  );
}

// ── Page-level layout: hero + sections (mirror of ProductsSettings) ─────

function Section({ icon, title, subtitle, children }) {
  return (
    <section className="bulk-section">
      <header className="bulk-section-head">
        <div className="bulk-section-icon">{icon}</div>
        <div className="bulk-section-text">
          <h2 className="bulk-section-title">{title}</h2>
          {subtitle && <p className="bulk-section-sub">{subtitle}</p>}
        </div>
      </header>
      <div className="bulk-section-fields">{children}</div>
    </section>
  );
}

// FieldCard variants — same shell as Product Settings, no Apply switch
// (this page is save-on-change, not bulk-apply). The `bulk-field--noswitch`
// modifier shifts the layout to skip the toggle column.
function FieldCard({ label, hint, children }) {
  return (
    <div className="bulk-field bulk-field--noswitch bulk-field--on">
      <div className="bulk-field-head">
        <div className="bulk-field-text">
          <span className="bulk-field-label">{label}</span>
          {hint && <span className="bulk-field-hint">{hint}</span>}
        </div>
      </div>
      <div className="bulk-field-value">{children}</div>
    </div>
  );
}

// ── Page ────────────────────────────────────────────────────────────────

export default function Documents() {
  const { projectId } = useOutletContext();
  const pq = `?project_id=${projectId}`;
  const fileRef = useRef(null);
  const [form, setForm]           = useState(null);
  const [uploading, setUploading] = useState(false);
  const [toast, setToast]         = useState('');
  const tref = useRef(null);

  const showToast = useCallback((msg) => {
    setToast(msg);
    if (tref.current) clearTimeout(tref.current);
    tref.current = setTimeout(() => setToast(''), 2400);
  }, []);

  // Bootstrap form state from the saved doc-settings row. Defaults match
  // backend's fallback values so the form is always editable even before
  // the merchant has saved anything.
  useEffect(() => {
    fetch(`${API_BASE}/api/document-settings${pq}`, { credentials: 'include' })
      .then(r => r.ok ? r.json() : null)
      .then(d => setForm(d || {
        style: 'modern', company_name: '', logo_url: null, address: '',
        tax_id_label: 'Tax ID', tax_id: '', contact_email: '', contact_phone: '',
        footer_note: '', accent_color: '#0071E3',
      }));
  }, [projectId]);

  // Save-on-change: every field commits as soon as the user moves on.
  // Debounce is provided implicitly by `onBlur` for text fields — clicks
  // on the StyleCard cards and the colour picker fire immediately.
  const persist = useCallback(async (patch) => {
    if (!form) return;
    const next = { ...form, ...patch };
    setForm(next);
    const res = await fetch(`${API_BASE}/api/document-settings${pq}`, {
      method: 'PUT', credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(next),
    });
    if (res.ok) showToast('Saved');
    else showToast('Save failed');
  }, [form, pq, showToast]);

  const upload = async (file) => {
    if (!file) return;
    setUploading(true);
    const fd = new FormData(); fd.append('file', file);
    try {
      const res = await fetch(`${API_BASE}/api/upload/image${pq}`, {
        method: 'POST', credentials: 'include', body: fd,
      });
      const data = await res.json();
      if (res.ok && data.url) persist({ logo_url: data.url });
      else showToast('Upload failed');
    } finally { setUploading(false); }
  };

  if (!form) return <div className="crm-placeholder">Loading…</div>;

  return (
    <>
      <h1 className="crm-page-title">Documents</h1>

      <div className="bulk-settings">

      {/* Template style — three preview cards. Each card is a button; clicking
          commits immediately so the merchant sees the preview in any
          freshly-generated PDF straight away. */}
      <Section icon={<FileText weight="duotone" />} title="Template style"
        subtitle="Pick the visual layout. You can change it any time.">
        <div className="doc-style-row">
          {STYLE_OPTIONS.map(opt => (
            <StyleCard key={opt.key} option={opt}
              current={form.style} onPick={(v) => persist({ style: v })} />
          ))}
        </div>
      </Section>

      {/* Company info — name + logo. Logo is uploaded to S3 via the standard
          /api/upload/image endpoint; the returned URL is stamped into PDF
          headers at 28×28 mm. */}
      <Section icon={<Buildings weight="duotone" />} title="Company info"
        subtitle="The brand identity printed at the top of every PDF.">
        <FieldCard label="Company / brand name"
          hint="Shown as the document header. Use the legal name if PDFs are used for tax filings.">
          <input className="crm-input" value={form.company_name || ''}
            onChange={e => setForm(f => ({ ...f, company_name: e.target.value }))}
            onBlur={e => persist({ company_name: e.target.value })}
            maxLength={200}
            placeholder="Acme Inc, ИП Иванов, etc." />
        </FieldCard>

        <FieldCard label="Logo"
          hint="Square or wide image. Rendered at 28×28 mm in the PDF header. PNG with transparent background recommended.">
          <input ref={fileRef} type="file" accept="image/*" className="hidden-input"
            onChange={e => upload(e.target.files?.[0])} />
          {form.logo_url ? (
            <div className="bk-svc-img-preview">
              <img src={form.logo_url} alt="" />
              <div className="bk-svc-img-actions">
                <button type="button" className="crm-submit-btn auth-btn-secondary"
                  onClick={() => fileRef.current?.click()} disabled={uploading}>
                  {uploading ? 'Uploading…' : 'Replace'}
                </button>
                <button type="button" className="auth-btn-danger"
                  onClick={() => persist({ logo_url: null })}>Remove</button>
              </div>
            </div>
          ) : (
            <button type="button" className="bk-svc-img-drop"
              onClick={() => fileRef.current?.click()} disabled={uploading}>
              {uploading ? 'Uploading…' : (
                <><UploadSimple weight="bold" size={20} /> <span>Click to upload a logo</span></>
              )}
            </button>
          )}
        </FieldCard>
      </Section>

      {/* Tax & legal — the bit that makes the PDF usable for actual accounting.
          BIN/VAT/EIN/ИНН label is configurable because the right code depends
          on the merchant's country. */}
      <Section icon={<IdentificationBadge weight="duotone" />} title="Tax & legal"
        subtitle="Identification used by your accountant or customer's bookkeeper.">
        <FieldCard label="Tax ID label"
          hint="Label shown before the number. Examples: BIN (KZ), VAT (EU), EIN (US), ИНН (RU).">
          <input className="crm-input" value={form.tax_id_label || ''}
            onChange={e => setForm(f => ({ ...f, tax_id_label: e.target.value }))}
            onBlur={e => persist({ tax_id_label: e.target.value })}
            maxLength={40}
            placeholder="Tax ID" />
        </FieldCard>
        <FieldCard label="Tax ID value"
          hint="Your registered tax/business identifier.">
          <input className="crm-input" value={form.tax_id || ''}
            onChange={e => setForm(f => ({ ...f, tax_id: e.target.value }))}
            onBlur={e => persist({ tax_id: e.target.value })}
            maxLength={80}
            placeholder="123456789012" />
        </FieldCard>
        <FieldCard label="Address"
          hint="Legal address printed under the company name.">
          <textarea className="crm-input bk-textarea" rows={3}
            value={form.address || ''}
            onChange={e => setForm(f => ({ ...f, address: e.target.value }))}
            onBlur={e => persist({ address: e.target.value })}
            placeholder="Street, city, postal code, country"
            maxLength={500} />
        </FieldCard>
      </Section>

      {/* Contact info — printed in the footer so customers know how to reach
          support after receiving the PDF. */}
      <Section icon={<EnvelopeSimple weight="duotone" />} title="Contact"
        subtitle="Where customers reply to questions about the PDF.">
        <FieldCard label="Contact email"
          hint="Printed in the footer. Recipients reply here for invoice questions.">
          <input className="crm-input" type="email" value={form.contact_email || ''}
            onChange={e => setForm(f => ({ ...f, contact_email: e.target.value }))}
            onBlur={e => persist({ contact_email: e.target.value })}
            maxLength={200}
            placeholder="billing@company.com" />
        </FieldCard>
        <FieldCard label="Contact phone"
          hint="International format recommended (e.g. +1 555 0100).">
          <input className="crm-input" value={form.contact_phone || ''}
            onChange={e => setForm(f => ({ ...f, contact_phone: e.target.value }))}
            onBlur={e => persist({ contact_phone: e.target.value })}
            maxLength={40}
            placeholder="+1 555 0100" />
        </FieldCard>
      </Section>

      {/* Visual customisation — accent colour (used by the Modern template
          for the banner and total row) + a free-form footer note. */}
      <Section icon={<Palette weight="duotone" />} title="Visual customisation"
        subtitle="Accent colour and footer text. Apply only to the Modern template.">
        <FieldCard label="Accent colour"
          hint="Used for the banner and total row in the Modern template. Hex format (#RRGGBB).">
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <input type="color" value={form.accent_color || '#0071E3'}
              onChange={e => persist({ accent_color: e.target.value })}
              style={{
                width: 40, height: 40, padding: 0, border: 'none',
                borderRadius: 999, cursor: 'pointer', background: 'transparent',
              }} />
            <input className="crm-input" value={form.accent_color || '#0071E3'}
              onChange={e => setForm(f => ({ ...f, accent_color: e.target.value }))}
              onBlur={e => persist({ accent_color: e.target.value })}
              maxLength={20}
              placeholder="#0071E3"
              style={{ maxWidth: 160 }} />
          </div>
        </FieldCard>
        <FieldCard label="Footer note"
          hint="Optional thank-you / terms line. Limited to 200 characters.">
          <input className="crm-input" value={form.footer_note || ''}
            onChange={e => setForm(f => ({ ...f, footer_note: e.target.value }))}
            onBlur={e => persist({ footer_note: e.target.value })}
            maxLength={200}
            placeholder="Thank you for your business" />
        </FieldCard>
      </Section>

      {toast && createPortal(<div className="auth-toast">{toast}</div>, document.body)}
      </div>
    </>
  );
}
