// PDF document branding — standalone page (extracted from Project Settings
// tabs because PDF setup deserves its own home, not a buried tab). Applies
// to invoices, acts, receipts and tickets — every PDF generated by the
// backend renders with these values stamped into the header / footer /
// accent stripes.
//
// Design mirrors the Product Settings "bulk-style" layout: one hero banner
// at top + Section components with icon / title / subtitle + bulk-field
// cards. Save-on-change for each field — no "Save all" button at the
// bottom. Toast pops on every successful save.

import { useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useOutletContext } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  FileText, Buildings, IdentificationBadge, Palette, UploadSimple,
  EnvelopeSimple,
} from '@phosphor-icons/react';
import { API_BASE } from '../../api.js';
import { presignedUpload } from '../../Utils/upload.js';
import '../../Style/Authentication.css';
import '../../Style/Products.css';
// Page-specific CSS — template-preview cards + logo uploader live
// here, isolated from Integrations.css / Booking.css where they were
// stranded before.
import '../../Style/Documents.css';

const STYLE_KEYS = ['modern', 'classic', 'minimal'];

function StyleCard({ option, current, onPick }) {
  const active = option.key === current;
  return (
    <button type="button"
      className={`doc-style-card${active ? ' doc-style-card--active' : ''}`}
      onClick={() => onPick(option.key)}>
      <div className={`doc-style-preview doc-style-preview--${option.key}`}>
        <div className="doc-style-preview-band" />
        <div className="doc-style-preview-line doc-style-preview-line--w70" />
        <div className="doc-style-preview-line doc-style-preview-line--w50" />
        <div className="doc-style-preview-line doc-style-preview-line--w90" />
        <div className="doc-style-preview-line doc-style-preview-line--w60" />
      </div>
      <div className="doc-style-name">{option.label}</div>
      <div className="doc-style-hint">{option.hint}</div>
    </button>
  );
}

// ── Page-level layout: hero + sections (mirror of ProductsSettings) ─────

function Section({ icon, title, subtitle, children }) {
  return (
    <section className="bulk-section">
      <header className="bulk-section-head">
        <div className="bulk-section-icon">{icon}</div>
        <div className="bulk-section-text">
          <h2 className="bulk-section-title">{title}</h2>
          {subtitle && <p className="bulk-section-sub">{subtitle}</p>}
        </div>
      </header>
      <div className="bulk-section-fields">{children}</div>
    </section>
  );
}

// FieldCard variants — same shell as Product Settings, no Apply switch
// (this page is save-on-change, not bulk-apply). The `bulk-field--noswitch`
// modifier shifts the layout to skip the toggle column.
function FieldCard({ label, hint, children }) {
  return (
    <div className="bulk-field bulk-field--noswitch bulk-field--on">
      <div className="bulk-field-head">
        <div className="bulk-field-text">
          <span className="bulk-field-label">{label}</span>
          {hint && <span className="bulk-field-hint">{hint}</span>}
        </div>
      </div>
      <div className="bulk-field-value">{children}</div>
    </div>
  );
}

// ── Page ────────────────────────────────────────────────────────────────

export default function Documents() {
  const { t } = useTranslation();
  const { projectId } = useOutletContext();
  const STYLE_OPTIONS = STYLE_KEYS.map(key => ({
    key,
    label: t(`project.documents.style.${key}`),
    hint: t(`project.documents.style.${key}Hint`),
  }));
  const pq = `?project_id=${projectId}`;
  const fileRef = useRef(null);
  const [form, setForm]           = useState(null);
  const [uploading, setUploading] = useState(false);
  const [toast, setToast]         = useState('');
  const tref = useRef(null);

  const showToast = useCallback((msg) => {
    setToast(msg);
    if (tref.current) clearTimeout(tref.current);
    tref.current = setTimeout(() => setToast(''), 2400);
  }, []);

  // Bootstrap form state from the saved doc-settings row. Defaults match
  // backend's fallback values so the form is always editable even before
  // the merchant has saved anything.
  useEffect(() => {
    fetch(`${API_BASE}/api/document-settings${pq}`, { credentials: 'include' })
      .then(r => r.ok ? r.json() : null)
      .then(d => setForm(d || {
        style: 'modern', company_name: '', logo_url: null, address: '',
        tax_id_label: 'Tax ID', tax_id: '', contact_email: '', contact_phone: '',
        footer_note: '', accent_color: '#0071E3',
      }));
  }, [projectId]);

  // Save-on-change: every field commits as soon as the user moves on.
  // Debounce is provided implicitly by `onBlur` for text fields — clicks
  // on the StyleCard cards and the colour picker fire immediately.
  const persist = useCallback(async (patch) => {
    if (!form) return;
    const next = { ...form, ...patch };
    setForm(next);
    const res = await fetch(`${API_BASE}/api/document-settings${pq}`, {
      method: 'PUT', credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(next),
    });
    if (res.ok) showToast(t('project.documents.saved'));
    else showToast(t('project.documents.saveFailed'));
  }, [form, pq, showToast]);

  const upload = async (file) => {
    if (!file) return;
    setUploading(true);
    try {
      const { url } = await presignedUpload(file, { pq, kind: 'image' });
      if (url) persist({ logo_url: url });
    } catch (e) {
      if (!e.planLimit) showToast(e.message || t('project.documents.uploadFailed'));
    } finally { setUploading(false); }
  };

  if (!form) return <div className="crm-placeholder">{t('project.documents.loading')}</div>;

  return (
    <>
      <h1 className="crm-page-title">{t('project.documents.title')}</h1>

      <div className="bulk-settings">

      {/* Template style — three preview cards. Each card is a button; clicking
          commits immediately so the merchant sees the preview in any
          freshly-generated PDF straight away. */}
      <Section icon={<FileText weight="duotone" />} title={t('project.documents.templateStyle')}
        subtitle={t('project.documents.templateStyleSub')}>
        <div className="doc-style-row">
          {STYLE_OPTIONS.map(opt => (
            <StyleCard key={opt.key} option={opt}
              current={form.style} onPick={(v) => persist({ style: v })} />
          ))}
        </div>
      </Section>

      {/* Company info — name + logo. Logo is uploaded to R2 via the presigned
          direct-to-R2 flow (Utils/upload.js); the returned URL is stamped into
          PDF headers at 28×28 mm. */}
      <Section icon={<Buildings weight="duotone" />} title={t('project.documents.companyInfo')}
        subtitle={t('project.documents.companyInfoSub')}>
        <FieldCard label={t('project.documents.companyName')}
          hint={t('project.documents.companyNameHint')}>
          <input className="crm-input" value={form.company_name || ''}
            onChange={e => setForm(f => ({ ...f, company_name: e.target.value }))}
            onBlur={e => persist({ company_name: e.target.value })}
            maxLength={200}
            placeholder={t('project.documents.companyNamePlaceholder')} />
        </FieldCard>

        <FieldCard label={t('project.documents.logo')}
          hint={t('project.documents.logoHint')}>
          <input ref={fileRef} type="file" accept="image/*" className="hidden-input"
            onChange={e => upload(e.target.files?.[0])} />
          {form.logo_url ? (
            <div className="doc-logo-preview">
              <img src={form.logo_url} alt="" />
              <div className="doc-logo-actions">
                <button type="button" className="crm-submit-btn auth-btn-secondary"
                  onClick={() => fileRef.current?.click()} disabled={uploading}>
                  {uploading ? t('project.documents.uploading') : t('project.documents.replace')}
                </button>
                <button type="button" className="auth-btn-danger"
                  onClick={() => persist({ logo_url: null })}>{t('project.documents.remove')}</button>
              </div>
            </div>
          ) : (
            <button type="button" className="doc-logo-drop"
              onClick={() => fileRef.current?.click()} disabled={uploading}>
              {uploading ? t('project.documents.uploading') : (
                <><UploadSimple weight="bold" size={20} /> <span>{t('project.documents.clickToUpload')}</span></>
              )}
            </button>
          )}
        </FieldCard>
      </Section>

      {/* Tax & legal — the bit that makes the PDF usable for actual accounting.
          BIN/VAT/EIN/ИНН label is configurable because the right code depends
          on the merchant's country. */}
      <Section icon={<IdentificationBadge weight="duotone" />} title={t('project.documents.taxLegal')}
        subtitle={t('project.documents.taxLegalSub')}>
        <FieldCard label={t('project.documents.taxIdLabel')}
          hint={t('project.documents.taxIdLabelHint')}>
          <input className="crm-input" value={form.tax_id_label || ''}
            onChange={e => setForm(f => ({ ...f, tax_id_label: e.target.value }))}
            onBlur={e => persist({ tax_id_label: e.target.value })}
            maxLength={40}
            placeholder={t('project.documents.taxIdLabelPlaceholder')} />
        </FieldCard>
        <FieldCard label={t('project.documents.taxIdValue')}
          hint={t('project.documents.taxIdValueHint')}>
          <input className="crm-input" value={form.tax_id || ''}
            onChange={e => setForm(f => ({ ...f, tax_id: e.target.value }))}
            onBlur={e => persist({ tax_id: e.target.value })}
            maxLength={80}
            placeholder="123456789012" />
        </FieldCard>
        <FieldCard label={t('project.documents.address')}
          hint={t('project.documents.addressHint')}>
          <textarea className="crm-input bk-textarea" rows={3}
            value={form.address || ''}
            onChange={e => setForm(f => ({ ...f, address: e.target.value }))}
            onBlur={e => persist({ address: e.target.value })}
            placeholder={t('project.documents.addressPlaceholder')}
            maxLength={500} />
        </FieldCard>
      </Section>

      {/* Contact info — printed in the footer so customers know how to reach
          support after receiving the PDF. */}
      <Section icon={<EnvelopeSimple weight="duotone" />} title={t('project.documents.contact')}
        subtitle={t('project.documents.contactSub')}>
        <FieldCard label={t('project.documents.contactEmail')}
          hint={t('project.documents.contactEmailHint')}>
          <input className="crm-input" type="email" value={form.contact_email || ''}
            onChange={e => setForm(f => ({ ...f, contact_email: e.target.value }))}
            onBlur={e => persist({ contact_email: e.target.value })}
            maxLength={200}
            placeholder="billing@company.com" />
        </FieldCard>
        <FieldCard label={t('project.documents.contactPhone')}
          hint={t('project.documents.contactPhoneHint')}>
          <input className="crm-input" value={form.contact_phone || ''}
            onChange={e => setForm(f => ({ ...f, contact_phone: e.target.value }))}
            onBlur={e => persist({ contact_phone: e.target.value })}
            maxLength={40}
            placeholder="+1 555 0100" />
        </FieldCard>
      </Section>

      {/* Visual customisation — accent colour (used by the Modern template
          for the banner and total row) + a free-form footer note. */}
      <Section icon={<Palette weight="duotone" />} title={t('project.documents.visualCustomisation')}
        subtitle={t('project.documents.visualCustomisationSub')}>
        <FieldCard label={t('project.documents.accentColour')}
          hint={t('project.documents.accentColourHint')}>
          <div className="doc-accent-row">
            <input type="color" className="doc-accent-swatch"
              value={form.accent_color || '#0071E3'}
              onChange={e => persist({ accent_color: e.target.value })} />
            <input className="crm-input doc-accent-hex"
              value={form.accent_color || '#0071E3'}
              onChange={e => setForm(f => ({ ...f, accent_color: e.target.value }))}
              onBlur={e => persist({ accent_color: e.target.value })}
              maxLength={20}
              placeholder="#0071E3" />
          </div>
        </FieldCard>
        <FieldCard label={t('project.documents.footerNote')}
          hint={t('project.documents.footerNoteHint')}>
          <input className="crm-input" value={form.footer_note || ''}
            onChange={e => setForm(f => ({ ...f, footer_note: e.target.value }))}
            onBlur={e => persist({ footer_note: e.target.value })}
            maxLength={200}
            placeholder={t('project.documents.footerNotePlaceholder')} />
        </FieldCard>
      </Section>

      {toast && createPortal(<div className="auth-toast">{toast}</div>, document.body)}
      </div>
    </>
  );
}
